name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install checkinstall -y
    - run: sudo checkinstall make make-pc-file
    - name: 上传
        with:
          name: Modest deb
          path: ${{ github.workspace }}/Modest/Modest/modest_20210120-1_amd64.deb
    - name: make
      run: make
    - name: make test
      run: make test
    - name: make 打包
      run: make make-pc-file
    - name: make install
      run: sudo make install
